# Generated by Django 3.2.7 on 2021-09-14 09:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('github_profile', '0003_auto_20210907_1451'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile1',
            fields=[
                ('username', models.CharField(default=None, max_length=30, primary_key=True, serialize=False)),
                ('first_name', models.CharField(default=None, max_length=30)),
                ('last_name', models.CharField(max_length=30, null=True)),
                ('avatar_url', models.CharField(max_length=100, null=True)),
                ('follower_count', models.IntegerField()),
                ('last_update', models.DateTimeField(auto_now_add=True)),
                ('repos', models.JSONField()),
            ],
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
