# Generated by Django 3.2.7 on 2021-09-18 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('github_profile', '0004_auto_20210914_1503'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('username', models.CharField(default=None, max_length=150, primary_key=True, serialize=False)),
                ('first_name', models.CharField(default=None, max_length=30)),
                ('last_name', models.CharField(max_length=30, null=True)),
                ('avatar_url', models.CharField(max_length=100, null=True)),
                ('follower_count', models.IntegerField()),
                ('last_update', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repo_name', models.CharField(max_length=100, null=True)),
                ('repo_stars', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='github_profile.profile')),
            ],
        ),
        migrations.DeleteModel(
            name='Profile1',
        ),
    ]
